Push changes to help auth/sync work.
Latest bug is:
Unhandled Error
Traceback (most recent call last):
  File "/Users/ds/code/indx/env/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/ds/code/indx/lib/indx/objectstore_types.py", line 107, in loop
    return_d.callback(True)
  File "/Users/ds/code/indx/env/lib/python2.7/site-packages/twisted/internet/defer.py", line 380, in callback
    self._startRunCallbacks(result)
  File "/Users/ds/code/indx/env/lib/python2.7/site-packages/twisted/internet/defer.py", line 488, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/Users/ds/code/indx/env/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/ds/code/indx/lib/indx/sync.py", line 285, in expanded_cb
    clientauth.auth_keys(local_key['private'], local_key_hash).addCallbacks(authed_cb, return_d.errback)
exceptions.AttributeError: Deferred instance has no attribute '__getitem__'